name: Excavator

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  excavator:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Scoop
        uses: MinoruSekine/setup-scoop@v4
        with:
          scoop_update: 'true'

      - name: Update Manifests
        shell: pwsh
        run: |
          $checkver = Join-Path (scoop prefix scoop) "bin\checkver.ps1"
          & $checkver * -Dir bucket -u

          # Clean up any side-effect files created by scoop tools
          if (Test-Path "install.ps1") { Remove-Item "install.ps1" -Force }

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          # Only add changes within the bucket directory
          git add bucket/
          
          if (git status --porcelain) {
            git commit -m "chore: update manifests"
            git push
          }
