name: Excavator

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  excavator:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Scoop
        uses: MinoruSekine/setup-scoop@v4
        with:
          scoop_update: 'true'

      - name: Update Manifests
        shell: pwsh
        run: |
          # Construct path to checkver.ps1 dynamically
          $checkver = Join-Path (scoop prefix scoop) "bin\checkver.ps1"
          Write-Host "Running checkver from: $checkver"
          
          # Execute checkver
          & $checkver * -u

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          if (git status --porcelain) {
            git commit -m "chore: update manifests"
            git push
          }
